[package]
name = "example-derived"
version = "0.0.0"
publish = false
# Inherited.
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ferrunix = { path = "../../ferrunix", features = ["multithread"] }
thiserror = "2"
