[workspace]
resolver = "2"
members = [
    "rusty-injector",
    "rusty-injector-macros",
]

[workspace.dependencies]
rusty-injector = { path = "./rusty-injector" }
rusty-injector-macros = { path = "./rusty-injector-macros" }
