[workspace]
allow_dirty = false
dependencies_update = false # update dependencies with `cargo update`
git_release_enable = true # enable GitHub releases
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_name = "Release {{ package }} v{{ version }}" # template for the PR name
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = false # don't add `--allow-dirty` to `cargo publish`
semver_check = true # enable API breaking changes checks
publish_timeout = "10m" # set a timeout for `cargo publish`

[[package]]
name = "ferrunix"
changelog_include = ["ferrunix-core", "ferrunix-macros"] # include commits from others in the changelog
changelog_update = true # enable changelog update
git_release_enable = true # enable GitHub releases
publish = true # enable `cargo publish`

[[package]]
name = "ferrunix-core"
changelog_update = true # enable changelog update
git_release_enable = false # disable GitHub releases
publish = true # enable `cargo publish`

[[package]]
name = "ferrunix-macros"
changelog_update = true # enable changelog update
git_release_enable = false # disable GitHub releases
publish = true # enable `cargo publish`

[[package]]
name = "xtask"
release = false # don't process this package

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
