[package]
name = "xtask"
version = "0.0.0"
publish = false
# Inherited.
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
xshell = "0.2"
