[package]
name = "ferrunix"
version = "0.1.0"
description = "A lightweight run-time dependency injection framework for Rust"
readme = "README.md"
# Inherited.
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

# [lints]
# workspace = true

[features]
default = ["multithread", "derive"]
multithread = ["ferrunix-core/multithread"]
derive = ["dep:ferrunix-macros"]

[dependencies]
ferrunix-core = { path = "../ferrunix-core", default-features = false, version = "0.1.0" }

# Optional dependencies
ferrunix-macros = { path = "../ferrunix-macros", optional = true, version = "0.1.0" }
